@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzgyMjU3OTR9.Zm3svWW3o9yW46E-9uYm3jtuQQ8ctCtceaLVmeEs0_I

@jwt2 = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NzgyMjg5ODF9.WcL0sSk5I8cu7bkzRvL6uodfMTl3q0NAEWAKyNon36g

### Sessions New (Supervisor)
POST http://localhost:3000/sessions.json  
Content-Type: application/json

{
  "email": "jim@test.com",
  "password": "password"
}
### Sessions New (Field Tech)
POST http://localhost:3000/sessions.json  
Content-Type: application/json

{
  "email": "gail@test.com",
  "password": "password"
}

### Users Index
GET http://localhost:3000/users.json
Authorization: Bearer {{jwt}}

### Users Show
GET http://localhost:3000/users/1.json

### Users Create
POST http://localhost:3000/users.json  
Content-Type: application/json

{
  "first_name": "Aladdin",
  "last_name": "Prince Ali",
  "email": "aladdin@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Users Update
PATCH http://localhost:3000/users/6.json  
Content-Type: application/json

{
  "password": "password",
  "password_confirmation": "password",
  "rig_id": 1
}

### User Destroy
DELETE http://localhost:3000/users/14.json 



########### RIG ##############
### Rig Index
GET http://localhost:3000/rigs.json 

### Rig Show
GET http://localhost:3000/rigs/1.json 

### Rig Create
POST http://localhost:3000/rigs.json  
Content-Type: application/json

{
  "name": "medic 2"
}

### Rig Destroy
DELETE http://localhost:3000/rigs/7.json 

######## Messages ############
### Message Index
GET http://localhost:3000/messages.json 

### Message Show
GET http://localhost:3000/messages/2.json 

### Message Create
POST http://localhost:3000/messages.json 
Content-Type: application/json

{
  "date": "2023-02-12 15:00:06",
  "shift": "First",
  "content": "Clean and well stocked.",
  "user_id": 3
}

### Message Update
PATCH http://localhost:3000/messages/2.json 
Content-Type: application/json

{
  "shift": "First",
  "date": "2023-02-15 19:00:06",
  "content": "Testing Update Action"
}

### Message Destroy
DELETE http://localhost:3000/messages/2.json 

########### CHECKLIST #############

### Checklist Index
GET http://localhost:3000/checklists.json 

### Checklist Show
GET http://localhost:3000/checklists/1.json 

### Checklist Create
POST http://localhost:3000/checklists.json 
Authorization: Bearer {{jwt}}
Content-Type: application/json

{

}

### Checklist Update
PATCH http://localhost:3000/checklists/2.json 
Content-Type: application/json

{
  "exterior_clean": true,
  "cones_actual": "15",
  "siren": true
}

### Checklist Destroy
DELETE http://localhost:3000/checklists/1.json