### Users Index
GET http://localhost:3000/users.json

### Users Show
GET http://localhost:3000/users/1.json

### Users Create
POST http://localhost:3000/users.json  
Content-Type: application/json

{
  "first_name": "Harry",
  "last_name": "Duggan",
  "email": "Harry@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Users Update
PATCH http://localhost:3000/users/7.json  
Content-Type: application/json

{
  "first_name": "Jacky",
  "email": "Jacky@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### User Destroy
DELETE http://localhost:3000/users/2.json 

### Sessions New
POST http://localhost:3000/sessions.json  
Content-Type: application/json

{
  "email": "Neil@test.com",
  "password": "password"
}
