### Users Index
GET http://localhost:3000/users.json

### Users Show
GET http://localhost:3000/users/1.json

### Users Create
POST http://localhost:3000/users.json  
Content-Type: application/json

{
  "first_name": "Aladdin",
  "last_name": "Prince Ali",
  "email": "Harry@test.com",
  "password": "password",
  "password_confirmation": "password",
  "rig_id": null
}

### Users Update
PATCH http://localhost:3000/users/6.json  
Content-Type: application/json

{
  "password": "password",
  "password_confirmation": "password",
  "rig_id": 1
}

### User Destroy
DELETE http://localhost:3000/users/2.json 

### Sessions New
POST http://localhost:3000/sessions.json  
Content-Type: application/json

{
  "email": "Neil@test.com",
  "password": "password"
}

### Rig Index
GET http://localhost:3000/rigs.json 

### Rig Show
GET http://localhost:3000/rigs/1.json 

### Rig Create
POST http://localhost:3000/rigs.json  
Content-Type: application/json

{
  "name": "medic 2"
}

### Rig Destroy
DELETE http://localhost:3000/rigs/2.json 